[package]
name = "saturn-collections"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
